---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: delete-me-too

enabled: true

stickinessProperty: rox.distinct_id

defaultValue:
  valueWrittenInCode: true

conditions:
  - allOf:
      - property:
          name: rox.platform
          operator: in-array
          operands:
            - value
            - valueee
    flagValue: true
