---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: f2

enabled: false

stickinessProperty: rox.distinct_id

defaultValue:
  valueWrittenInCode: true

conditions:
  - allOf:
      - property:
          name: cp-boolean-1
          operator: is-true
      - property:
          name: cp-boolean-1
          operator: is-false
    flagValue: false
