---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: testflag1

enabled: true

stickinessProperty: rox.distinct_id

defaultValue:
  - percentage: 0
    from: 2025-08-08T15:17:00Z
  - percentage: 50
    from: 2025-08-08T15:22:00Z
  - percentage: 75
    from: 2025-08-20T15:27:00Z
  - percentage: 100
    from: 2025-08-22T15:32:00Z

conditions: []
