---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: testflag2

enabled: true

stickinessProperty: rox.distinct_id

defaultValue:
  valueWrittenInCode: true

conditions:
  - allOf:
      - anyOf:
          - group:
              name: rebel-forces
    flagValue: blue
