---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: fm-test-flag

enabled: true

stickinessProperty: rox.distinct_id

defaultValue: true

conditions:
  - allOf:
      - property:
          name: cp-romain
          operator: is-true
    flagValue: true
  - allOf:
      - property:
          name: cp-romain
          operator: is-false
    flagValue: false
