---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: f2

enabled: true

stickinessProperty: rox.distinct_id

defaultValue:
  - percentage: 50
    option: true
  - percentage: 50
    option: false

conditions: []
