---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: showMessage

enabled: true

stickinessProperty: rox.distinct_id

defaultValue: true

conditions:
  - anyOf:
      - anyOf:
          - group:
              name: tg-1
      - property:
          name: rox.platform
          operator: in-array
          operands:
            - "22"
    flagValue: false
