---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: blat6

enabled: false

stickinessProperty: rox.distinct_id

defaultValue:
  valueWrittenInCode: true

conditions:
  - allOf:
      - anyOf:
          - group:
              name: TG1
    flagValue: false
